### ISSUE TITLE
some error as plugin of caldera platform 

### ISSUE THREAD

**Issue by lazyermax** [mitre/debrief#40]
**Describe the bug**
There are some error in terminal when i show graph in caldera platform 
`Traceback (most recent call last):
  File "/home/nsfocus/caldera/plugins/debrief/app/debrief_gui.py", line 82, in graph
    graph = await graphs[graph_type](operations)
RuntimeError: coroutine raised StopIteration`

**Comment by mchan143** [comment]
Can you provide what version you're using? I've seen a similar error occasionally when switching between CALDERA versions, can you see if pulling the latest version and clearing your browser cache fixes the issue?

**Comment by wbooth** [comment]
If you get back to this and your issue is unresolved please feel free to re-open!
