### ISSUE TITLE
Mapping TTPs and CVEs

### ISSUE THREAD

**Issue by afarao** [mitre/debrief#48]
Hi! I am new here!
Is there any way to link TTPs and CVEs through the Caldera?
Through the Pathfinder plugin I have received the network topology including the CVES, and then I have created an operation using as adversary the Thief.
Once the operation is done, I use the Debrief plugin to see how the operation is completed and then I can see the used TTPs.
Is there any way to export which CVEs are linked to each used TTP?
Thanks in advance!

**Comment by wbooth** [comment]
Hi @afarao! Yes -- you can tag abilities as seen here: https://github.com/center-for-threat-informed-defense/caldera_pathfinder/blob/master/data/abilities/initial-access/315f8fcc-c05a-4db0-9f9a-5daade661540.yml#L11-L12
you can tag with a CVE or any other piece of information
